version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/1_init.up.sql:/docker-entrypoint-initdb.d/1_init.up.sql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./config/local.yaml:/app/config/local.yaml

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: